FROM futtetennista/hakyll:latest

RUN apt-get update && apt-get install --yes \
    imagemagick \
    make

RUN stack upgrade && stack --resolver lts-13.6 install \
    hakyll-favicon \
    hakyll-sass

EXPOSE 8000

ENTRYPOINT ["bash"]
