FROM futtetennista/hakyll:latest

RUN apt-get update && apt-get install --yes \
  curl \
  imagemagick \
  make

# https://github.com/commercialhaskell/stackage/issues/3132
RUN curl -sSL https://get.haskellstack.org/ | sh -s - -f

COPY stack.yaml.ext /root/.stack/global-project/stack.yaml

RUN stack --resolver lts-13.6 install \
  hakyll-favicon \
  hakyll-sass
