FROM futtetennista/hakyll:latest

RUN apt-get update && apt-get install --yes \
    imagemagick \
    make

RUN stack --resolver lts-9.14 install \
    hakyll-favicon \
    hakyll-sass

EXPOSE 8000

ENTRYPOINT ["bash"]
